// The public surface of the client class, FROZEN as a type test.
// Generated on 2026-08-21 from dist/index.d.ts BEFORE client.ts was split into
// mixins. The split spreads the methods over partial classes, and this test
// proves that each of the 85 methods still exists on ScalebrowserClient for a
// consumer. A method lost in a refactor becomes a type error here, not a silent
// gap in the .d.ts.
import { describe, expectTypeOf, it } from "vitest"

import type { ScalebrowserClient } from "../src/index"

describe("ScalebrowserClient public surface", () => {
  it("carries every method the published 0.2.0 d.ts carried", () => {
    expectTypeOf<ScalebrowserClient>().toHaveProperty("attachExtension")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bindInbox")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bulkAssignExtensions")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bulkAssignProxy")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bulkCreateProfiles")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bulkDelete")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bulkStart")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("bulkStop")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("checkProxy")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("checkProxyConfig")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("connectCdp")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("createGroup")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("createInbox")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("createPreset")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("createProfile")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("createProxy")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteCredential")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteGroup")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteInbox")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteInterruptionRule")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteLibraryExtension")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteLibraryExtensionVersion")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deletePasskey")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deletePreset")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteProfile")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("deleteProxy")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("detachExtension")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("events")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("exportCredentials")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("exportSession")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getAccount")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getActivity")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getArtifact")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getAudit")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getGroup")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getInboxBindings")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getLibraryExtension")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getMetrics")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getPersonaConstraints")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getPreset")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getProfile")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getProxy")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getRun")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("getRunShot")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("health")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("importCredentials")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("importSession")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("launch")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listCredentials")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listExtensions")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listGroups")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listInboxes")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listInterruptionLocks")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listInterruptionRules")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listLibraryExtensions")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listPasskeys")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listPresets")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listProfileIds")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listProfiles")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listProxies")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listRunSteps")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("listRuns")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("putArtifact")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("putCredential")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("ready")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("revealCookies")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("revealCredential")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("sendInput")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("setInterruptionLock")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("setInterruptionRule")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("setToken")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("setVaultPassword")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("startAudit")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("startProfile")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("stopProfile")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("subscribeEvents")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("unbindInbox")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("updateGroup")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("updateInbox")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("updatePreset")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("updateProfile")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("updateProxy")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("uploadExtension")
    expectTypeOf<ScalebrowserClient>().toHaveProperty("vaultStatus")
  })
})
